from typing import Protocol, runtime_checkable


@runtime_checkable
class Savable(Protocol):
    def namespace(self) -> str: ...
    def version(self) -> str: ...
    def save(self, dataHandler) -> dict: ...
    def deserialize(self, dataHandler): ...
